name: Delete older releases and workflows
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@v0.1.0
        with:
          delete_releases: true
          releases_keep_latest: 1
          delete_workflows: true
          delete_tags: true
          workflows_keep_day: 10
          gh_token: ${{ secrets.GITHUB_TOKEN }}
